[package]
name = "luvyn"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
luvyn-core = { path = "../luvyn-core" }
serde.workspace = true
serde_json.workspace = true
blake3.workspace = true
clap = { version = "4", features = ["derive"] }
axum = "0.8"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "signal", "time"] }
notify = "8"
rust-embed = "8"
mime_guess = "2"
webbrowser = "1"
rand = "0.9"
ignore = "0.4"

[dev-dependencies]
tempfile = "3"

